version: 0.0
os: linux

files:
  - source: ./target/ROOT.war
    destination: /opt/tomcat/latest/webapps

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 180
      runas: ubuntu