version: 0.0
os: linux

files:
  - source: ./target/ROOT.war
    destination: /opt/tomcat/latest/webapps
  - source: ./cloudwatch-fonfig.json
    destination: /opt

hooks:
  ApplicationStop:
    - location: scripts/appStop.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/appStart.sh
      timeout: 180
      runas: ubuntu