name: pr_check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          mysql version: '8.0'
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}
      - name: Build with Maven
        run: mvn -B test
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          S3_BUCKET_NAME: webapptest.zhenyu.ye
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REALM: desktop

